Repository pawgistics/pawgistics, pull requests merged in 2018-02, with the labels that each got.

#17 Dynamo
  src/server/api/index.js
  src/server/models/dog.js
  src/server/models/foster.js
  src/server/models/index.js
  src/server/models/user.js
  src/server/util/dog.js
  src/server/util/foster.js
  src/server/util/populateDev.js
Labels: AWS

#20 Fix auth reducer
  src/client/reducers/auth.js
Labels: bug

#22 Add API test routes
  src/server/api/index.js
  src/server/api/test.api.js
Labels: API
